[package]
name = "sleep"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_sleep"
path = "sleep.rs"

[dependencies]
getopts = "0.2.18"

[dependencies.uucore]
version = "0.0.1"
features = ["parse_time"]

[[bin]]
name = "sleep"
path = "../../uumain.rs"
