[package]
name = "numfmt"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_numfmt"
path = "numfmt.rs"

[dependencies]
getopts = "0.2.18"
uucore = "0.0.1"

[[bin]]
name = "numfmt"
path = "../../uumain.rs"
