[package]
name = "dircolors"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_dircolors"
path = "dircolors.rs"

[dependencies]
glob = "0.3.0"
uucore = "0.0.1"

[[bin]]
name = "dircolors"
path = "../../uumain.rs"
