version: 2
mergeable:
- when: pull_request.*, pull_request_review.*
  validate:
  - do: or
    validate:
    - do: approvals
      min:
        count: 1
        message: "non-trivial PRs need to be reviewed by everyone before it can be merged."
    - do: label
      must_include:
        regex: '^dependencies$'
        message: "If your PR is trivial and doesn't require review, simply add the trivial tag."
