[package]
name = "tsort"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_tsort"
path = "tsort.rs"

[dependencies]
getopts = "0.2.18"
uucore = "0.0.1"

[[bin]]
name = "tsort"
path = "../../uumain.rs"
