[package]
name = "nice"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_nice"
path = "nice.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.42"
uucore = "0.0.1"

[[bin]]
name = "nice"
path = "../../uumain.rs"
