[package]
name = "link"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_link"
path = "link.rs"

[dependencies]
libc = "0.2.42"
uucore = "0.0.1"

[[bin]]
name = "link"
path = "../../uumain.rs"
