[package]
name = "seq"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_seq"
path = "seq.rs"

[dependencies]
getopts = "0.2.18"
uucore = "0.0.1"

[[bin]]
name = "seq"
path = "../../uumain.rs"
