[package]
name = "tr"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_tr"
path = "tr.rs"

[dependencies]
getopts = "0.2.18"
bit-set = "0.5.0"
fnv = "1.0.5"
uucore = "0.0.1"

[[bin]]
name = "tr"
path = "../../uumain.rs"
