[package]
name = "wc"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_wc"
path = "wc.rs"

[dependencies]
getopts = "0.2.18"
uucore = "0.0.1"

[[bin]]
name = "wc"
path = "../../uumain.rs"
