[package]
name = "users"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_users"
path = "users.rs"

[dependencies]
getopts = "0.2.18"

[dependencies.uucore]
features = ["utmpx"]
version = "0.0.1"

[[bin]]
name = "users"
path = "../../uumain.rs"
