[package]
name = "tee"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_tee"
path = "tee.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.42"
uucore = "0.0.1"

[[bin]]
name = "tee"
path = "../../uumain.rs"
