[package]
name = "build-script"
version = "0.1.0"
authors = ["Thomas Guillemard <me@thog.eu>"]
edition = "2018"

[dependencies]
tar = "0.4"
flate2 = { version = "1.0", features = ["rust_backend"] }

[workspace]
