[package]
name = "paste"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_paste"
path = "paste.rs"

[dependencies]
getopts = "0.2.18"
uucore = "0.0.1"

[[bin]]
name = "paste"
path = "../../uumain.rs"
