[package]
name = "yes"
version = "0.0.1"
authors = []
description = "Repeatedly output a line with all specified STRING(s), or 'y'."
build = "../../mkmain.rs"

[lib]
name = "uu_yes"
path = "yes.rs"

[dependencies]
clap = "2.32"
uucore = { version = "0.0.1", features = ["zero-copy"] }

[features]
latency = []
default = []

[[bin]]
name = "yes"
path = "../../uumain.rs"
