[package]
name = "split"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_split"
path = "split.rs"

[dependencies]
getopts = "0.2.18"
uucore = "0.0.1"

[[bin]]
name = "split"
path = "../../uumain.rs"
