[package]
name = "mktemp"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_mktemp"
path = "mktemp.rs"

[dependencies]
uucore = "0.0.1"
getopts = "0.2.18"
rand = "0.5"
tempfile = "2.1.5"

[[bin]]
name = "mktemp"
path = "../../uumain.rs"
