[package]
name = "stdbuf"
version = "0.0.1"
authors = []
build = "build.rs"

[lib]
name = "uu_stdbuf"
path = "stdbuf.rs"

[dependencies]
getopts = "0.2.18"
tempdir = "0.3.7"
uucore = "0.0.1"

[build-dependencies]
libstdbuf = { path="libstdbuf" }

[[bin]]
name = "stdbuf"
path = "../../uumain.rs"
