[package]
name = "shuf"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_shuf"
path = "shuf.rs"

[dependencies]
getopts = "0.2.18"
rand = "0.5"
uucore = "0.0.1"

[[bin]]
name = "shuf"
path = "../../uumain.rs"
