[package]
name = "df"
version = "0.1.0"
authors = ["Thomas Guillemard <me@thog.eu>"]
license = "Apache-2.0 OR MIT"
edition = "2018"

[dependencies]
sunrise-libuser = { path = "../libuser", default-features = false, features = ["build-for-std-app"] }
