[package]
name = "realpath"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_realpath"
path = "realpath.rs"

[dependencies]
getopts = "0.2.18"

[dependencies.uucore]
version = "0.0.1"
features = ["fs"]

[[bin]]
name = "realpath"
path = "../../uumain.rs"
