[package]
name = "echo"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_echo"
path = "echo.rs"

[dependencies]
uucore = "0.0.1"

[[bin]]
name = "echo"
path = "../../uumain.rs"
