[package]
name = "mkfifo"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_mkfifo"
path = "mkfifo.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.42"
uucore = "0.0.1"

[[bin]]
name = "mkfifo"
path = "../../uumain.rs"
