[package]
name = "tty"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_tty"
path = "tty.rs"

[dependencies]
getopts = "0.2.18"
libc = "0.2.42"

[dependencies.uucore]
version = "0.0.1"
features = ["fs"]

[[bin]]
name = "tty"
path = "../../uumain.rs"
