[package]
name = "swipc-parser"
version = "0.1.0"
authors = ["roblabla <unfiltered@roblab.la>"]
edition = "2018"
description = "Parser for the SwIPC file format"

[dependencies]
pest = "2.1"
pest_derive = "2.1"
