[package]
name = "sum"
version = "0.0.1"
authors = []
build = "../../mkmain.rs"

[lib]
name = "uu_sum"
path = "sum.rs"

[dependencies]
getopts = "0.2.18"
uucore = "0.0.1"

[[bin]]
name = "sum"
path = "../../uumain.rs"
